# Generated by Django 5.1.5 on 2025-09-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('documento', models.CharField(help_text='DNI/CUIT u otro documento', max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('ASESOR', 'Asesor'), ('CLIENTE', 'Cliente'), ('GERENTE', 'Gerente'), ('OTRO', 'Otro')], db_index=True, default='CLIENTE', max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
